# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Brandon Summers
subtitle: 
sidebar: none
author: Brandon Summers

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: evopix
github_repo_count: 3
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: bsummers82
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus:
    shortname: brandonsummers
    show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-29125605-1

# Facebook Like
facebook_like: false

# Diigo
diigo_user: bsummers82
diigo_count: 5